### ISSUE TITLE
Binary format of STL

### ISSUE THREAD

**Issue by jr23mx** [beeb/step2stl#3]
It would be nice if you support the binary version of STL because the outputs are quite heavy

**Comment by beeb** [comment]
Should be doable easily with https://crates.io/crates/stl_io :+1:

**Comment by beeb** [comment]
Adding this here for reference, seems the `ASCIIMode` flag can be used to change the format to binary https://dev.opencascade.org/doc/refman/html/class_stl_a_p_i___writer.html

**Comment by beeb** [comment]
This is supported in the new version I just released! Unfortunately I broke the auto-updater so it must be installed manually.
